upstream_package_name: python-nitrate
downstream_package_name: python-nitrate

specfile_path: python-nitrate.spec
synced_files: [python-nitrate.spec]

actions:
  create-archive:
  - make tarball
  get-current-version:
  - make version

jobs:
- job: copr_build
  metadata:
    targets:
    - fedora-all
    - epel-9
    - epel-8
    - epel-7
  trigger: pull_request

- job: copr_build
  trigger: commit
  metadata:
    branch: main
    targets:
    - fedora-all
    - epel-9
    - epel-8
    - epel-7
    list_on_homepage: True
    preserve_project: True
    owner: psss
    project: python-nitrate
